Information section (basic)
shitalke/relp-frontend pull request #17
Opened 2022-08-21 07:59 UTC by wes-chen

- Basic information section implementation
- replace png with all svg

TODO:
ordering needs to be figured out
dynamic height needs to be implemented

2022-08-22 21:44 UTC, parth4apple requested changes

2022-08-22 21:44 UTC, parth4apple commented on src/components/Info/index.js
> +    <>
dont need fragment

2022-08-22 21:44 UTC, parth4apple commented on src/components/Info/style.js
>  export const InfoString = styled.div`
why not use Text component?

2022-08-22 21:44 UTC, parth4apple commented on src/components/InfoTable/index.js
> + * Info Table - styling for the 2 column info table
you dont need a component to wrap things. u could move infoStyle to /Info/style.js and use it to wrap InfoContainer in /Info/index.js -- nit pick, but would help minimize # of components

2022-08-22 21:46 UTC, parth4apple commented on src/components/InfoTable/style.js
> +  max-width: 420px;
make this larger -- looks really bad on not phone views, putting it at 80% or something would look good

2022-08-22 21:47 UTC, parth4apple commented on src/components/Info/style.js
>  export const IconImg = styled.img`
delete this if ur not using it

2022-08-22 21:48 UTC, parth4apple commented on src/components/Info/style.js
> +  padding-top: 2.5px;
make this and padding-bottom like 10 or something -- looks too cramped rn

2022-08-22 21:54 UTC, wes-chen commented on src/components/Info/index.js
> +    <>
ok

2022-08-22 21:54 UTC, wes-chen commented on src/components/Info/style.js
>  export const InfoString = styled.div`
i don't

2022-08-22 21:55 UTC, wes-chen commented on src/components/InfoTable/index.js
> + * Info Table - styling for the 2 column info table
no, I can't, because I need to do the map operation on InfoContainer inside one InfoTable, so it's not one InfoContainer per InfoTable

2022-08-22 22:03 UTC, wes-chen commented on src/components/Info/style.js
> +  padding-top: 2.5px;
ok

2022-08-22 22:03 UTC, wes-chen commented on src/components/Info/style.js
>  export const IconImg = styled.img`
ok

2022-08-22 22:03 UTC, wes-chen commented on src/components/InfoTable/style.js
> +  max-width: 420px;
see discussion on slack

2022-08-23 00:18 UTC, parth4apple approved these changes

2022-08-23 00:18 UTC, parth4apple approved these changes

2022-08-23 00:19 UTC, merged