Feature/parth4apple/comments
shitalke/relp-frontend pull request #4
Opened 2022-07-07 04:29 UTC by parth4apple

## Changes
- Created the comments and replies display based on the high fidelity designs
- Added styled component to dependency list

## To do
- like comment functionality
- reply connection to backend
- add a new comment field 
- new comment connection to backend

2022-07-07 05:05 UTC, wes-chen requested changes
few comments other than the ones we discussed on slack

2022-07-07 05:05 UTC, wes-chen commented on src/Restroom/RestroomCommentChain.js
> +      <CommentComponent
why is this hard coded?

2022-07-07 05:05 UTC, wes-chen commented on src/Restroom/RestroomCommentChain.js
> +function CommentComponent(props) {
can this be moved out into a different file

2022-07-07 05:05 UTC, wes-chen commented on src/Restroom/RestroomCommentChain.js
> +      console.log(response.data);
we don't need to log this anymore

2022-07-07 05:05 UTC, wes-chen commented on src/Restroom/RestroomCommentChain.js
> +            likes={4}
is this information not available from the API?

2022-07-07 05:05 UTC, wes-chen commented on src/Restroom/RestroomCommentChain.js
> +function Reply() {
different file like earlier

2022-07-07 06:29 UTC, wes-chen requested changes
more comments

2022-07-07 06:29 UTC, wes-chen commented on src/Restroom/RestroomDiscussion.js
> +            There are {this.props.num_comments} comments on this restroom.{" "}
You can remove this, it was just a placeholder

2022-07-07 06:29 UTC, wes-chen commented on src/Restroom/RestroomCommentChain.js
> +      <CommentThread
why are we doing one `CommentThread` and then a map afterwards?

2022-07-07 06:31 UTC, parth4apple commented on src/Restroom/RestroomCommentChain.js
> +      <CommentComponent
fixed

2022-07-07 06:31 UTC, parth4apple commented on src/Restroom/RestroomCommentChain.js
> +            likes={4}
Info on rating is not available through the api without using relational aspects

2022-07-07 06:34 UTC, parth4apple commented on src/Restroom/RestroomCommentChain.js
> +      <CommentThread
Because there is one base comment and then its replies

2022-07-08 03:05 UTC, wes-chen approved these changes

2022-07-08 03:06 UTC, merged